   version: '3.8'

   services:
     app:
       build:
         context: ..
         dockerfile: Dockerfiles/Dockerfile
       ports:
         - "5000:5000"  # Map host port 5000 to container port 10000
       environment:
         - NODE_ENV=production
         - PORT=5000  # Match the port exposed in Dockerfile
         - MONGO_URI=mongodb+srv://storeadmin:admin12345@cluster0.hzdvdne.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
       volumes:
         - uploads_data:/app/BACKEND/uploads
       restart: unless-stopped

   volumes:
     uploads_data: 